spring:
  elasticsearch:
    uris: http://localhost:9200
  data:
    elasticsearch:
      repositories:
        enabled: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: recommendation-group
      auto-offset-reset: earliest
